# This workflow will perform the code review on each code change.
# It uses "actions/cache" and turborepo in order to perform tasks only on changed files.

name: "Code Review"

on:
  push:
    branches: ["main"]
    paths:
      - packages/**
      - scripts/**
  pull_request:
    types: [opened, synchronize]
    paths:
      - packages/**
      - scripts/**
  workflow_dispatch: {}

jobs:
  code_review:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version-file: ".node-version"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build the project
        run: yarn build

      - name: "Code review"
        run: yarn run code-review

      - name: "Coverage"
        run: yarn coverage

      - name: "Upload to codecov.io"
        uses: codecov/codecov-action@v4
